//! Embed the shipped rule pack in the binary.
//!
//! A pack that lives only in the repo is not shipped: `cargo install rwr`
//! copies the binary and nothing else, so `rwr check performance` has to
//! resolve against something compiled in.

use std::path::{Path, PathBuf};

fn main() {
    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let rules = root.join("rules");
    println!("cargo:rerun-if-changed={}", rules.display());

    let mut found = Vec::new();
    collect(&rules, &mut found);
    // Path order, so the embedded pack applies exactly as the directory does.
    found.sort();

    let mut out = String::from(
        "// Generated by build.rs from rules/. Do not edit.\n\
         pub(crate) static BUILTIN: &[(&str, &str)] = &[\n",
    );
    for path in &found {
        let id = path
            .strip_prefix(&rules)
            .expect("under rules/")
            .with_extension("")
            .to_string_lossy()
            .replace('\\', "/");
        out.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            id,
            path.display().to_string()
        ));
        println!("cargo:rerun-if-changed={}", path.display());
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("out dir")).join("builtin_rules.rs");
    std::fs::write(dest, out).expect("write generated rules");
}

fn collect(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(&path, out);
        } else if matches!(
            path.extension().and_then(|e| e.to_str()),
            Some("yml" | "yaml")
        ) {
            out.push(path);
        }
    }
}
