#!/usr/bin/env python3
"""Generate the node comparator from Prism's vendored schema (D36).

Equality is variant + atoms + children; locations never participate. Generating
rather than hand-writing means a Prism upgrade that adds a field cannot silently
drop it from equality -- regenerating produces a diff, and the parity test fails
until it is applied.

    ./script/gen-compare.py > src/pattern/generated.rs
"""
import glob, json, sys

paths = glob.glob(
    "/Users/dpepper/.cargo/registry/src/*/ruby-prism-*/vendor/prism-*/config.json"
)
if not paths:
    sys.exit("could not find the ruby-prism vendored config.json")
cfg = json.load(open(sorted(paths)[-1]))

NODE_NAMES = {n["name"] for n in cfg["nodes"]}
CHILD = {"node", "node?", "node[]"}
NAME = {"constant", "constant?", "constant[]"}
VALUE = {"string", "integer", "double", "uint8", "uint32"}

out = []
w = out.append
w("//! GENERATED by script/gen-compare.py -- do not edit by hand.")
w("//!")
w("//! Child and atom extraction for every Prism node (D36). Equality is")
w("//! variant + atoms + children; location fields are deliberately absent")
w("//! here, because spelling is opt-in through `where:` predicates rather")
w("//! than baked into node equality.")
w("")
w("use super::compare::Atom;")
w("use ruby_prism::Node;")
w("")
w("/// Immediate child nodes, in field order.")
w("#[allow(clippy::too_many_lines, unused_variables)]")
w("pub(crate) fn children<'pr>(node: &Node<'pr>) -> Vec<Node<'pr>> {")
w("    let mut out = Vec::new();")
w("    match node {")
for n in cfg["nodes"]:
    name = n["name"]
    fields = [f for f in n.get("fields", []) if f["type"] in CHILD]
    if not fields:
        continue
    w(f"        Node::{name} {{ .. }} => {{")
    snake = ''.join('_'+c.lower() if c.isupper() else c for c in name).lstrip('_')
    w(f"            let Some(n) = node.as_{snake}() else {{ return out }};")
    for f in fields:
        acc, ty = f["name"], f["type"]
        # `kind` is either a concrete node type ("ArgumentsNode" -> a typed
        # accessor needing `.as_node()`), a semantic constraint
        # ("non-void expression"), the generic "Node", or a list -- and all
        # three of those already yield `Node`.
        k = f.get("kind")
        typed = isinstance(k, str) and k in NODE_NAMES
        conv = ".as_node()" if typed else ""
        if ty == "node":
            w(f"            out.push(n.{acc}(){conv});")
        elif ty == "node?":
            w(f"            if let Some(x) = n.{acc}() {{ out.push(x{conv}); }}")
        else:
            w(f"            out.extend(n.{acc}().iter());")
    w("        }")
w("        _ => {}")
w("    }")
w("    out")
w("}")
w("")
w("/// Duplicate a node handle.")
w("///")
w("/// `Node` holds raw pointers and derives neither `Clone` nor `Copy`, but a")
w("/// handle is just those pointers -- copying one is free and does not")
w("/// duplicate the underlying tree, which the parse result still owns.")
w("#[allow(clippy::too_many_lines)]")
w("pub(crate) fn dup<'pr>(node: &Node<'pr>) -> Node<'pr> {")
w("    match node {")
for n in cfg["nodes"]:
    nm = n["name"]
    w(f"        Node::{nm} {{ parser, pointer, marker }} => Node::{nm} {{ parser: *parser, pointer: *pointer, marker: *marker }},")
w("    }")
w("}")
w("")
w("/// Atoms: names and values that are not child nodes. `CallNode::name` lives")
w("/// here -- comparing variant and children alone would match `foo(a)`")
w("/// against `bar(a)`.")
w("#[allow(clippy::too_many_lines, unused_variables)]")
w("pub(crate) fn atoms<'pr>(node: &Node<'pr>) -> Vec<Atom> {")
w("    let mut out = Vec::new();")
w("    match node {")
for n in cfg["nodes"]:
    name = n["name"]
    fields = [f for f in n.get("fields", []) if f["type"] in NAME | VALUE]
    if not fields:
        continue
    snake = ''.join('_'+c.lower() if c.isupper() else c for c in name).lstrip('_')
    w(f"        Node::{name} {{ .. }} => {{")
    w(f"            let Some(n) = node.as_{snake}() else {{ return out }};")
    for f in fields:
        acc, ty = f["name"], f["type"]
        if ty == "constant":
            w(f"            out.push(Atom::name(n.{acc}().as_slice()));")
        elif ty == "constant?":
            w(f"            if let Some(c) = n.{acc}() {{ out.push(Atom::name(c.as_slice())); }}")
        elif ty == "constant[]":
            w(f"            out.extend(n.{acc}().iter().map(|c| Atom::name(c.as_slice())));")
        elif ty == "string":
            w(f"            out.push(Atom::value(n.{acc}()));")
        elif ty == "integer":
            # Debug on Prism's Integer prints its pointer, not its value.
            w(f"            out.push(Atom::integer(&n.{acc}()));")
        else:
            w(f"            out.push(Atom::debug(&n.{acc}()));")
    w("        }")
w("        _ => {}")
w("    }")
w("    out")
w("}")
print("\n".join(out))
